[project]
name = "AstroSpace"
version = "1.0.0"
description = "Astrophotography blog app built in Flask\PostgreSQL"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"